!include "SOURCES.MAC"

bin\psychics.exe: $(srcs)
    tlink /c /s @RUNTIME @LISTOBJS , @EXEC , @EXEC , @LISTLIBS

obj\Error.obj: src\Error.c
	tcc -ml -G -nobj -c -Isrc src\Error.c

obj\Timer.obj: src\Timer.c
	tcc -ml -G -nobj -c -Isrc src\Timer.c

obj\DMA.obj: src\memory\DMA.c
	tcc -ml -G -nobj -c -Isrc src\memory\DMA.c

obj\PMem.obj: src\memory\PMem.c
	tcc -ml -G -nobj -c -Isrc src\memory\PMem.c

obj\Key.obj: src\input\Key.c
	tcc -ml -G -nobj -c -Isrc src\input\Key.c

obj\Joy.obj: src\input\Joy.c
	tcc -ml -G -nobj -c -Isrc src\input\Joy.c

obj\AudCtrl.obj: src\audio\AudCtrl.c
	tcc -ml -G -nobj -c -Isrc src\audio\AudCtrl.c

obj\SBlaster.obj: src\audio\SBlaster.c
	tcc -ml -G -nobj -c -Isrc src\audio\SBlaster.c

obj\FMSynth.obj: src\audio\FMSynth.c
	tcc -ml -G -nobj -c -Isrc src\audio\FMSynth.c

obj\RADFile.obj: src\audio\RADFile.c
	tcc -ml -G -nobj -c -Isrc src\audio\RADFile.c

obj\RADPlay.obj: src\audio\RADPlay.c
	tcc -ml -G -nobj -c -Isrc src\audio\RADPlay.c

obj\WAVFile.obj: src\audio\WAVFile.c
	tcc -ml -G -nobj -c -Isrc src\audio\WAVFile.c

obj\PCXFile.obj: src\graphics\PCXFile.c
	tcc -ml -G -nobj -c -Isrc src\graphics\PCXFile.c

obj\BMPFile.obj: src\graphics\BMPFile.c
	tcc -ml -G -nobj -c -Isrc src\graphics\BMPFile.c

obj\Render.obj: src\graphics\Render.c
	tcc -ml -G -nobj -c -Isrc src\graphics\Render.c

obj\Matrix.obj: src\types\Matrix.c
	tcc -ml -G -nobj -c -Isrc src\types\Matrix.c

obj\Engine.obj: src\Engine.c
	tcc -ml -G -nobj -c -Isrc src\Engine.c

obj\Game.obj: src\Game.c
	tcc -ml -G -nobj -c -Isrc src\Game.c

obj\MAIN.obj: src\MAIN.c
	tcc -ml -G -nobj -c -Isrc src\MAIN.c

obj\Types.obj: src\types\Types.c
	tcc -ml -G -nobj -c -Isrc src\types\Types.c

obj\LinkList.obj: src\types\LinkList.c
	tcc -ml -G -nobj -c -Isrc src\types\LinkList.c

obj\SBRs.obj: src\audio\SBRs.asm
	tcc -ml -G -nobj -c -Isrc src\audio\SBRs.asm

obj\Animator.obj: src\graphics\Animator.c
	tcc -ml -G -nobj -c -Isrc src\graphics\Animator.c

obj\TileMap.obj: src\tiles\TileMap.c
	tcc -ml -G -nobj -c -Isrc src\tiles\TileMap.c